using DBTemplateHandler.Core.Database;
using DBTemplateHandler.Core.TemplateHandlers.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DBTemplateHandler.Core.TemplateHandlers.Context.Columns
{
    public class AutoColumnIndexColumnContextHandler : AbstractColumnTemplateContextHandler
    {
        public AutoColumnIndexColumnContextHandler(ITemplateHandler templateHandlerNew) : base(templateHandlerNew) { }

        public override string StartContext => "{:TDB:TABLE:COLUMN:AUTO:FOREACH:CURRENT:INDEX";
        public override string EndContext => "::}";
        public int DefaultIndex => 0;
        private string DefaultAutoIndexAsString => $"{DefaultIndex}";
        public override bool isStartContextAndEndContextAnEntireWord => true;
        public override string ContextActionDescription => "Is replaced by the current auto generated value column index in the current table auto generated value column collection iterated";
        
        public override string ProcessContext(string StringContext, IDatabaseContext databaseContext)
        {
            if (databaseContext == null) throw new ArgumentNullException(nameof(databaseContext));
            base.ControlContext(StringContext,databaseContext);
            string TrimedStringContext = TrimContextFromContextWrapper(StringContext);
            base.ControlContextContent(TrimedStringContext);
            if (databaseContext.Table == null) return DefaultAutoIndexAsString;
            IColumnModel columnModel = databaseContext.Column;
            IList<IColumnModel> columnList = databaseContext.Table.Columns;
            if (columnList == null) return DefaultAutoIndexAsString;
            var parentAutoColumn = columnList.Where(m => m.IsAutoGeneratedValue).ToList();
            if (parentAutoColumn.Any(m => columnModel == m)) return parentAutoColumn.IndexOf(columnModel).ToString();
            return DefaultAutoIndexAsString;
        }
    }
}
