using DBTemplateHandler.Core.Database;
using System;
using System.Collections.Generic;
using System.Text;

namespace DBTemplateHandler.Persistance.Serializable
{
    public class PersistableDatabaseModel
    {
        public string TypeSetName { get; set; }
        public string Name { get; set; }
        public List<PersistableTableModel> Tables { get; set; }
    }

    public class PersistableTableModel
    {
        public string Name { get; set; }
        public List<PersistableColumnModel> Columns { get; set; }
    }

    public class PersistableColumnModel : IColumnModel
    {
        public bool IsAutoGeneratedValue { get; set ; }
        public bool IsNotNull { get ; set ; }
        public bool IsPrimaryKey { get ; set ; }
        public string Name { get ; set ; }
        public string Type { get ; set ; }
        public ITableModel ParentTable { get ; set ; }
    }

}
