using DBTemplateHandler.Core.Database;
using DBTemplateHandler.Core.TemplateHandlers.Handlers;
using System;
using System.Text;

namespace DBTemplateHandler.Core.TemplateHandlers.Context.Tables
{
    public class ForEachNotAutoGeneratedValueColumnTableContextHandler : AbstractLoopColumnTableTemplateContextHandler
    {

        public ForEachNotAutoGeneratedValueColumnTableContextHandler(ITemplateHandler templateHandlerNew) : base(templateHandlerNew) { }
        public override string StartContext { get => "{:TDB:TABLE:COLUMN:NOT:AUTO:FOREACH["; }
        public override string EndContext { get => "]::}"; }
        public override bool isStartContextAndEndContextAnEntireWord => false;
        public override string ContextActionDescription => "Is replaced by the intern context as many time as there is not auto generated value column in the table";


        public override string processContext(string StringContext)
        {
            return ProcessContext(StringContext, new ProcessorDatabaseContext() { Table = TableModel });
        }
        public override string ProcessContext(string StringContext, IDatabaseContext databaseContext)
        {
            if (databaseContext == null) throw new ArgumentNullException(nameof(databaseContext));
            if (StringContext == null)
                throw new Exception($"The provided {nameof(StringContext)} is null");
            ITableModel table = TableModel;
            if (table == null)
                throw new Exception($"The {nameof(TableModel)} is not set");

            string TrimedStringContext = TrimContextFromContextWrapper(StringContext);
            StringBuilder stringBuilder = new StringBuilder();
            foreach(ColumnModel currentColumn in table.Columns)
            {
                if (!currentColumn.IsAutoGeneratedValue)
                {
                    string treated =
                            TemplateHandler.HandleTableColumnTemplate
                                (TrimedStringContext, currentColumn);
                    treated = TemplateHandler.
                            HandleFunctionTemplate
                                            (treated, table.ParentDatabase,
                                                    table, currentColumn,null);
                    stringBuilder.Append(treated);
                }
            }
            return stringBuilder.ToString();
        }

    }
}
