using System;
using System.Collections.Generic;
using System.Text;

namespace DBTemplateHander.DatabaseModel.Import.Importer.SQLServerImporterComponents.Models
{
    public class SQLServerForeignKeysModel : SQLServerObjectModel
    {
        /// <summary>
        /// ID of the referenced object.
        /// </summary>
        public int referenced_object_id { get; set; }
        /// <summary>
        /// ID of the key index within the referenced object.
        /// </summary>
        public int key_index_id { get; set; }
        /// <summary>
        /// FOREIGN KEY constraint is disabled.
        /// </summary>
        public bool is_disabled { get; set; }

        /// <summary>
        /// FOREIGN KEY constraint was created by using the NOT FOR REPLICATION option.
        /// </summary>
        public bool is_not_for_replication { get; set; }

        /// <summary>
        /// FOREIGN KEY constraint has not been verified by the system.
        /// </summary>
        public bool is_not_trusted { get; set; }

        /// <summary>
        /// The referential action that was declared for this FOREIGN KEY when a delete happens.
        /// 0 = No action
        /// 1 = Cascade
        /// 2 = Set null
        /// 3 = Set default
        /// </summary>
        public byte delete_referential_action { get; set; }

        /// <summary>
        /// Description of the referential action that was declared for this FOREIGN KEY when a delete occurs:
        /// NO_ACTION,
        /// CASCADE,
        /// SET_NULL,
        /// SET_DEFAULT
        /// </summary>
        public string delete_referential_action_desc { get; set; }

        /// <summary>
        /// The referential action that was declared for this FOREIGN KEY when an update happens.
        /// 0 = No action
        /// 1 = Cascade
        /// 2 = Set null
        /// 3 = Set default
        /// </summary>
        public byte update_referential_action { get; set; }

        /// <summary>
        /// Description of the referential action that was declared for this FOREIGN KEY when an update happens:
        /// </summary>
        public string update_referential_action_desc { get; set; }
        /// <summary>
        /// <value>true </value> when Name was generated by the system.
        /// <value>false </value> when Name was supplied by the user.
        /// </summary>
        public bool is_system_named { get; set; }
    }
}
