using DBTemplateHandler.Core.Database;
using DBTemplateHandler.Core.TemplateHandlers.Context.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Handlers;
using DBTemplateHandler.Core.UnitTests.ModelImplementation;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.Text;

namespace DBTemplateHandler.Core.UnitTests.TemplateHandlers.Context.Columns
{
    [TestFixture]
    public class IsAutoColumnAFirstAutoColumnContextHandlerUnitTests
    {
        private IsAutoColumnAFirstAutoColumnContextHandler _tested;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _tested = new IsAutoColumnAFirstAutoColumnContextHandler(TemplateHandlerBuilder.Build(null));
        }

        [Test]
        public void IsStartContextAndEndContextAnEntireWordShouldReturnFalse()
        {
            Assert.IsFalse(_tested.isStartContextAndEndContextAnEntireWord);
        }

        [Test]
        public void ContextActionDescriptionShouldReturnTheAccurateDescription()
        {
            Assert.AreEqual("Is replaced by the inner context when the current column is the first column from the iterated auto generated value column collection", _tested.ContextActionDescription);
        }

        [Test]
        public void ProcessContextShouldThrowAnExceptionWhenStringContextIsNull()
        {
            Assert.Throws<Exception>(() => _tested.ProcessContext(null,
                new ProcessorDatabaseContext() { Column = new ColumnModelForTest() { } }));
        }

        [Test]
        public void ShouldThrowAnArgumentNullExceptionWhenDatabaseContextIsNull()
        {
            Assert.Throws<ArgumentNullException>(() => _tested.ProcessContext("Hello world", null));
        }

        [Test]
        public void ProcessContextShouldThrowAnExceptionWhenColumnModelIsNull()
        {
            Assert.Throws<Exception>(() => _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}",
                new ProcessorDatabaseContext() { Column = null }));
        }

        [Test]
        public void ProcessContextShouldThrowAnExceptionWhenColumnModelHasSetParentTableToNull()
        {
            Assert.Throws<Exception>(() => _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}",
                new ProcessorDatabaseContext() { Column = new ColumnModelForTest() { }, Table = null }));
        }

        [Test]
        public void ProcessContextShouldThrowAnExceptionWhenColumnsAreNotSetInColumnModelParentTable()
        {
            Assert.Throws<Exception>(() => _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}",
                new ProcessorDatabaseContext() { Column = new ColumnModelForTest() { }, Table = new TableModelForTest() { Columns = null } }));
        }

        [Test]
        public void ProcessContextShouldThrowAnExceptionWhenColumnsInColumnModelParentTableIsAnEmptyList()
        {
            Assert.Throws<Exception>(() => _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}",
                new ProcessorDatabaseContext()
                {
                    Column = new ColumnModelForTest() { },
                    Table = new TableModelForTest() { Columns = new List<IColumnModel>() }
                }));
        }

        [Test]
        public void ProcessContextShouldReturnAnEmptyStringWhenThereIsNoAutogeneratedValueColumnInColumnList()
        {
            var databaseContext =
                new ProcessorDatabaseContext()
                {
                    Column = new ColumnModelForTest() { IsAutoGeneratedValue = true },
                    Table = new TableModelForTest() { Columns = new List<IColumnModel>() { new ColumnModelForTest() { IsAutoGeneratedValue = false } } }
                };
            var actual = _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}", databaseContext);
            Assert.AreEqual(string.Empty, actual);
        }

        [Test]
        public void ProcessContextShouldReturnAnEmptyStringWhenTheColumnModelIsNotAutogeneratedValue()
        {
            var columnModel = new ColumnModelForTest() { IsAutoGeneratedValue = false };
            var parentTable = new TableModelForTest() { Columns = new List<IColumnModel>() { columnModel } };
            var databaseContext =
                new ProcessorDatabaseContext()
                {
                    Column = columnModel,
                    Table = parentTable
                };
            var actual = _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}", databaseContext);
            Assert.AreEqual(string.Empty, actual);
        }

        [Test]
        public void ProcessContextShouldReturnAnEmptyStringWhenTheAutogeneratedValueColumnModelIsNotTheFirstAutogeneratedValueColumnModel()
        {
            var columnModel = new ColumnModelForTest() { IsAutoGeneratedValue = true };
            var parentTable = new TableModelForTest()
            {
                Columns = new List<IColumnModel>()
                { new ColumnModelForTest() { Name = "Another Autogenerated Value Column", IsAutoGeneratedValue = true }, columnModel }
            };
            var databaseContext =
                new ProcessorDatabaseContext()
                {
                    Column = columnModel,
                    Table = parentTable
                };
            var actual = _tested.ProcessContext($"{_tested.StartContext}HelloWorld{_tested.EndContext}", databaseContext);
            Assert.AreEqual(string.Empty, actual);
        }

        [Test]
        public void ProcessContextShouldReturnAnContextStringValueWhenTheAutoGeneratedValueColumnModelIsTheFirstAutoGeneratedValueColumnModel()
        {
            var columnModel = new ColumnModelForTest() { IsAutoGeneratedValue = true };
            var parentTable = new TableModelForTest()
            {
                Columns = new List<IColumnModel>()
                { columnModel, new ColumnModelForTest() { Name = "Another Autogenerated Value Column", IsIndexed = true }  }
            };
            var databaseContext =
                new ProcessorDatabaseContext()
                {
                    Column = columnModel,
                    Table = parentTable
                };
            var expected = "HelloWorld";
            var actual = _tested.ProcessContext($"{_tested.StartContext}{expected}{_tested.EndContext}", databaseContext);
            Assert.AreEqual(expected, actual);
        }


        [Test]
        public void ProcessContextShouldReturnAnContextStringValueWhenTheAutoGeneratedValueColumnModelIsTheFirstAutoGeneratedValueColumnModelButNotTheFirstElementOfColumn()
        {
            var columnModel = new ColumnModelForTest() { IsAutoGeneratedValue = true };
            var parentTable = new TableModelForTest()
            {
                Columns = new List<IColumnModel>()
                {
                    new ColumnModelForTest() { Name = "Another column which is not autogenerated value column",IsAutoGeneratedValue=false },
                    columnModel,
                    new ColumnModelForTest() { Name = "Another autogenerated value column", IsAutoGeneratedValue = true }
                }
            };
            var databaseContext =
                new ProcessorDatabaseContext()
                {
                    Column = columnModel,
                    Table = parentTable
                };
            var expected = "HelloWorld";
            var actual = _tested.ProcessContext($"{_tested.StartContext}{expected}{_tested.EndContext}", databaseContext);
            Assert.AreEqual(expected, actual);
        }
    }
}
