namespace DBTemplateHandler.Core.Database
{
    public interface IColumnModel
    {
        bool IsAutoGeneratedValue { get; set; }
        bool IsNotNull { get; set; }
        bool IsPrimaryKey { get; set; }
        string Name { get; set; }
        string Type { get; set; }
        int ValueMaxSize { get; set; }
        public ITableModel ParentTable { get; set; }
    }
}