using DBTemplateHandler.Core.Database;
using DBTemplateHandler.Core.Template;
using DBTemplateHandler.Core.TemplateHandlers.Handlers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBTemplateHandler.Studio.Data
{
    public class DBTemplateService
    {
        private readonly InputModelHandler inputModelHandler = new InputModelHandler();
        public DBTemplateService()
        {
            
        }

        public Task<ITemplateModel> GetTemplateModel()
        {
            return Task.FromResult((new TemplateModel()
            {
                TemplatedFileContent = "Coucou",
                TemplatedFilePath = "test.txt",
            } as ITemplateModel));
        }

        public IList<IHandledTemplateResultModel> Process(ITemplateModel templateModel)
        {
            IDatabaseModel databaseModel = new DatabaseModel()
            {
                Name = "TestDatabase",
                Tables = new List<ITableModel>()
                {
                    new TableModel()
                    {
                        Name = "FirstTable",
                        Columns = new List<IColumnModel>()
                        {
                            new ColumnModel()
                            {
                                Name = "FirstColumn",
                                IsNotNull = true,
                                IsPrimaryKey = true,
                                Type = "VARCHAR",
                                IsAutoGeneratedValue = true,
                            },
                            new ColumnModel()
                            {
                                Name = "SecondColumn",
                                IsNotNull = true,
                                IsPrimaryKey = true,
                                Type = "INTEGER",
                                IsAutoGeneratedValue = true,
                            }
                        }
                    }
                }
            };

            

            IDatabaseTemplateHandlerInputModel databaseTemplateHandlerInputModel = new DatabaseTemplateHandlerInputModel()
            {
                DatabaseModel = databaseModel,
                TemplateModels = new List<ITemplateModel>()
                {
                    templateModel
                }
            };
            var result = inputModelHandler.Process(databaseTemplateHandlerInputModel);
            return result;
        }
    }
}
