using DBTemplateHandler.Core.TemplateHandlers.Context.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Context.Constraints;
using DBTemplateHandler.Core.TemplateHandlers.Context.Database;
using DBTemplateHandler.Core.TemplateHandlers.Context.Functions;
using DBTemplateHandler.Core.TemplateHandlers.Context.PreprocessorDeclarations;
using DBTemplateHandler.Core.TemplateHandlers.Context.Tables;
using DBTemplateHandler.Core.TemplateHandlers.Handlers;
using DBTemplateHandler.Service.Contracts.TypeMapping;
using System.Collections.Generic;
using System.Linq;

namespace DBTemplateHandler.Core.TemplateHandlers.Context
{
    public class TemplateContextHandlerRegister
    {
        private readonly IList<ITemplateContextHandler> _contextHandlers = new List<ITemplateContextHandler>(){ };

        public TemplateContextHandlerRegister(ITemplateHandler templateHandler, IList<ITypeMapping> typeMappings)
        {
            _contextHandlers =
            new List<ITemplateContextHandler>()
            {
                //Preprocessors contextes
                new MappingDeclarePreprcessorContextHandler(templateHandler),
                //Column contextes
                new AutoColumnIndexColumnContextHandler(templateHandler),
                new ColumnIndexColumnContextHandler(templateHandler),
                new ColumnNameColumnContextHandler(templateHandler),
                new ColumnValueConvertTypeColumnContextHandler(templateHandler,typeMappings),
                new ColumnValueTypeColumnContextHandler(templateHandler),
                new ColumnValueMaxSizeColumnContextHandler(templateHandler),
                new IsAutoColumnAFirstAutoColumnContextHandler(templateHandler),
                new IsAutoColumnALastAutoColumnContextHandler(templateHandler),
                new IsAutoColumnNotAFirstAutoColumnContextHandler(templateHandler),
                new IsAutoColumnNotALastAutoColumnContextHandler(templateHandler),
                new IsColumnAFirstColumnContextHandler(templateHandler),
                new IsColumnALastColumnContextHandler(templateHandler),
                new IsColumnAutoGeneratedValueColumnContextHandler(templateHandler),
                new IsColumnNotAFirstColumnContextHandler(templateHandler),
                new IsColumnNotALastColumnContextHandler(templateHandler),
                new IsColumnNotAutoGeneratedValueColumnContextHandler(templateHandler),
                new IsColumnNotNullValueColumnContextHandler(templateHandler),
                new IsColumnNullValueColumnContextHandler(templateHandler),
                new IsColumnNotPrimaryKeyColumnContextHandler(templateHandler),
                new IsColumnPrimaryKeyColumnContextHandler(templateHandler),
                new IsNotAutoColumnAFirstAutoColumnContextHandler(templateHandler),
                new IsNotAutoColumnALastAutoColumnContextHandler(templateHandler),
                new IsNotAutoColumnNotAFirstAutoColumnContextHandler(templateHandler),
                new IsNotAutoColumnNotALastAutoColumnContextHandler(templateHandler),
                new IsNotNullColumnAFirstAutoColumnContextHandler(templateHandler),
                new IsNotNullColumnALastAutoColumnContextHandler(templateHandler),
                new IsNotPrimaryColumnAFirstAutoColumnContextHandler(templateHandler),
                new IsNotPrimaryColumnALastAutoColumnContextHandler(templateHandler),
                new IsNotPrimaryColumnNotAFirstAutoColumnContextHandler(templateHandler),
                new IsNotPrimaryColumnNotALastAutoColumnContextHandler(templateHandler),
                new IsPrimaryColumnAFirstPrimaryColumnContextHandler(templateHandler),
                new IsPrimaryColumnALastPrimaryColumnContextHandler(templateHandler),
                new IsPrimaryColumnNotAFirstAutoColumnContextHandler(templateHandler),
                new IsPrimaryColumnNotALastAutoColumnContextHandler(templateHandler),
                new IsIndexedColumnAFirstIndexedColumnContextHandler(templateHandler),
                new IsIndexedColumnALastIndexedColumnContextHandler(templateHandler),
                new IsIndexedColumnNotAFirstIndexedColumnContextHandler(templateHandler),
                new IsIndexedColumnNotALastIndexedColumnContextHandler(templateHandler),
                new IsNotIndexedColumnAFirstIndexedColumnContextHandler(templateHandler),
                new IsNotIndexedColumnALastIndexedColumnContextHandler(templateHandler),
                new IsNotIndexedColumnNotAFirstIndexedColumnContextHandler(templateHandler),
                new IsNotIndexedColumnNotALastIndexedColumnContextHandler(templateHandler),
                new WhenColumnIsIndexedColumnContextHandler(templateHandler),
                new WhenColumnIsNotIndexedColumnContextHandler(templateHandler),
                new NotAutoColumnIndexColumnContextHandler(templateHandler),
                new NotNullColumnIndexColumnContextHandler(templateHandler),
                new NotPrimaryColumnIndexColumnContextHandler(templateHandler),
                new PrimaryColumnIndexColumnContextHandler(templateHandler),
                //Constraints
                new ConstraintNameConstraintContextHandler(templateHandler),
                //Table
                new ForEachAutoGeneratedValueColumnTableContextHandler(templateHandler),
                new ForEachColumnTableContextHandler(templateHandler),
                new ForEachConstraintTableContextHandler(templateHandler),
                new ForEachIndexedColumnTableContextHandler(templateHandler),
                new ForEachNotIndexedColumnTableContextHandler(templateHandler),
                new ForEachNotAutoGeneratedValueColumnTableContextHandler(templateHandler),
                new ForEachNotNullColumnTableContextHandler(templateHandler),
                new ForEachNotPrimaryKeyColumnTableContextHandler(templateHandler),
                new ForEachPrimaryKeyColumnTableContextHandler(templateHandler),
                new TableNameTableContextHandler(templateHandler),
                new TableSchemaTableContextHandler(templateHandler),
                new WhenHasAutoGeneratedValueColumnTableContextHandler(templateHandler),
                new WhenHasIndexColumnTableContextHandler(templateHandler),
                new WhenHasNotIndexColumnTableContextHandler(templateHandler),
                new ForEachTablesForeignVisitContextHanlder(templateHandler),
                //Database
                new DatabaseNameDatabaseContextHandler(templateHandler),
                new ConnectionStringDatabaseContextHandler(templateHandler),
                new ForEachTableDatabaseContextHandler(templateHandler),
                //Functions
                new FirstLetterToUpperCaseFunctionTemplateHandler(templateHandler),
                new ReplaceWithFunctionTemplateHandler(templateHandler),
        };
        }


        public IList<T> GetHanlders<T>() where T : ITemplateContextHandler
        {
            return _contextHandlers
                .Where(m => m is T && m != null)
                .Select(m => (T)m)
                .ToList();
        }

    }
}
