using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DBTemplateHandler.Core.TemplateHandlers.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Context.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Context.Database;
using DBTemplateHandler.Core.TemplateHandlers.Context.Functions;
using DBTemplateHandler.Core.TemplateHandlers.Context.Tables;
using DBTemplateHandler.Core.TemplateHandlers.Utilities;

namespace DBTemplateHandler.Core.TemplateHandlers.Context
{
    public class TemplateContextHandlerPackageProvider
    {
        private const string NEW_LINE_CHAR = "\t\n";

        //Column part
        private static IEnumerable<AbstractColumnTemplateContextHandler> DefaultLoadColumnContextHandlerDefault()
        {
            List<AbstractColumnTemplateContextHandler> result = new List<AbstractColumnTemplateContextHandler>();
            result.Add(new AutoColumnIndexColumnContextHandler());
            result.Add(new ColumnIndexColumnContextHandler());
            result.Add(new ColumnNameColumnContextHandler());
            result.Add(new ColumnValueConvertTypeColumnContextHandler());
            result.Add(new ColumnValueTypeColumnContextHandler());
            result.Add(new IsAutoColumnAFirstAutoColumnContextHandler());
            result.Add(new IsAutoColumnALastAutoColumnContextHandler());
            result.Add(new IsAutoColumnNotAFirstAutoColumnContextHandler());
            result.Add(new IsAutoColumnNotALastAutoColumnContextHandler());
            result.Add(new IsColumnAFirstColumnContextHandler());
            result.Add(new IsColumnALastColumnContextHandler());
            result.Add(new IsColumnAutoGeneratedValueColumnContextHandler());
            result.Add(new IsColumnNotAFirstColumnContextHandler());
            result.Add(new IsColumnNotALastColumnContextHandler());
            result.Add(new IsColumnNotAutoGeneratedValueColumnContextHandler2());
            result.Add(new IsColumnNotNullValueColumnContextHandler());
            result.Add(new IsColumnNotPrimaryKeyColumnContextHandler());
            result.Add(new IsColumnPrimaryKeyColumnContextHandler());
            result.Add(new IsNotAutoColumnAFirstAutoColumnContextHandler());
            result.Add(new IsNotAutoColumnALastAutoColumnContextHandler());
            result.Add(new IsNotAutoColumnNotAFirstAutoColumnContextHandler());
            result.Add(new IsNotAutoColumnNotALastAutoColumnContextHandler());
            result.Add(new IsNotNullColumnAFirstAutoColumnContextHandler());
            result.Add(new IsNotNullColumnALastAutoColumnContextHandler());
            result.Add(new IsNotPrimaryColumnAFirstAutoColumnContextHandler());
            result.Add(new IsNotPrimaryColumnALastAutoColumnContextHandler());
            result.Add(new IsNotPrimaryColumnNotAFirstAutoColumnContextHandler());
            result.Add(new IsNotPrimaryColumnNotALastAutoColumnContextHandler());
            result.Add(new IsPrimaryColumnAFirstAutoColumnContextHandler());
            result.Add(new IsPrimaryColumnALastAutoColumnContextHandler());
            result.Add(new IsPrimaryColumnNotAFirstAutoColumnContextHandler());
            result.Add(new IsPrimaryColumnNotALastAutoColumnContextHandler());
            result.Add(new NotAutoColumnIndexColumnContextHandler());
            result.Add(new NotNullColumnIndexColumnContextHandler());
            result.Add(new NotPrimaryColumnIndexColumnContextHandler());
            result.Add(new PrimaryColumnIndexColumnContextHandler());
            return result;
        }

        public static List<string>
            GetDefaultLoadAndOriginalLoadColumnContextHandlerDifferenceSignatureArray()
        {
            List<string> result = new List<string>();
            IEnumerable<AbstractColumnTemplateContextHandler> defaultLoad = DefaultLoadColumnContextHandlerDefault();
            IEnumerable<AbstractColumnTemplateContextHandler> originalLoad = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractColumnTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }

        public static IEnumerable<AbstractColumnTemplateContextHandler> getAllColumnContextHandler()
        {
            return DefaultLoadColumnContextHandlerDefault();
        }

        public static IDictionary<String, AbstractColumnTemplateContextHandler> getStartContextWrapperStringIndexedColumnContextHandlerMap()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> result =
                    new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractColumnTemplateContextHandler> getEndContextWrapperStringIndexedColumnContextHandlerMap()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> result =
                    new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllColumnContextHandlerSignature()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers =
                    getAllColumnContextHandler();

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("Column context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getColumnHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAColumnHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getColumnHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnColumnHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsAColumnHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnColumnHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractColumnTemplateContextHandler getStartContextCorrespondingColumnContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractColumnTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedColumnContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Column Part End


        //Table Part
        private static IEnumerable<AbstractTableTemplateContextHandler> DefaultLoadTableContextHandlerDefault()
        {
            List<AbstractTableTemplateContextHandler> result = new List<AbstractTableTemplateContextHandler>();
            result.Add(new ForEachAutoGeneratedValueColumnTableContextHandler());
            result.Add(new ForEachColumnTableContextHandler());
            result.Add(new ForEachNotAutoGeneratedValueColumnTableContextHandler());
            result.Add(new ForEachNotNullColumnTableContextHandler());
            result.Add(new ForEachNotPrimaryKeyColumnTableContextHandler());
            result.Add(new ForEachPrimaryKeyColumnTableContextHandler());
            result.Add(new TableNameTableContextHandler());
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadTableContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractTableTemplateContextHandler> defaultLoad = DefaultLoadTableContextHandlerDefault();
            IEnumerable<AbstractTableTemplateContextHandler> originalLoad = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractTableTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }

        public static IEnumerable<AbstractTableTemplateContextHandler> getAllTableContextHandler()
        {
            return DefaultLoadTableContextHandlerDefault();
        }

        public static IDictionary<String, AbstractTableTemplateContextHandler> getStartContextWrapperStringIndexedTableContextHandlerMap()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> result = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractTableTemplateContextHandler> getEndContextWrapperStringIndexedTableContextHandlerMap()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> result = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllTableContextHandlerSignature()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers =
                    getAllTableContextHandler();

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("Table context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getTableHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsATableHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getTableHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnTableHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsATableHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnTableHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractTableTemplateContextHandler getStartContextCorrespondingTableContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractTableTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedTableContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //End Table context


        //Database context Handler Part
        private static IEnumerable<AbstractDatabaseTemplateContextHandler> DefaultLoadDatabaseContextHandlerDefault()
        {
            List<AbstractDatabaseTemplateContextHandler> result = new List<AbstractDatabaseTemplateContextHandler>();
            result.Add(new DatabaseNameDatabaseContextHandler());
            result.Add(new ForEachTableDatabaseContextHandler());
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadDatabaseContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractDatabaseTemplateContextHandler> defaultLoad = DefaultLoadDatabaseContextHandlerDefault();
            IEnumerable<AbstractDatabaseTemplateContextHandler> originalLoad = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractDatabaseTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }
        public static IEnumerable<AbstractDatabaseTemplateContextHandler> getAllDatabaseContextHandler()
        {
            return DefaultLoadDatabaseContextHandlerDefault();
        }

        public static IDictionary<String, AbstractDatabaseTemplateContextHandler> getStartContextWrapperStringIndexedDatabaseContextHandlerMap()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> result = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractDatabaseTemplateContextHandler> getEndContextWrapperStringIndexedDatabaseContextHandlerMap()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> result = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllDatabaseContextHandlerSignature()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers =
                    getAllDatabaseContextHandler();

            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.Append("Database context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static string getDatabaseHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsADatabaseHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            var abatractTemplateContextHandlers = getAllDatabaseContextHandler();
            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }
            return result;
        }

        public static string getDatabaseHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            if (!isSubmittedStringContainsAnDatabaseHandlerEndContextWord(submittedString)) return result;
            var abatractTemplateContextHandlers = getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsADatabaseHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractDatabaseTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnDatabaseHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;
            var abstractTemplateContextHandlers = getAllDatabaseContextHandler();
            return abstractTemplateContextHandlers.Any(current => 
                submittedString.Contains(current.getEndContextStringWrapper()));
        }

        public static AbstractDatabaseTemplateContextHandler getStartContextCorrespondingDatabaseContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractDatabaseTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedDatabaseContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Database end context

        //Function start context
        private static IEnumerable<AbstractFunctionTemplateContextHandler> DefaultLoadFunctionContextHandlerDefault()
        {
            List<AbstractFunctionTemplateContextHandler> result = new List<AbstractFunctionTemplateContextHandler>();
            result.Add(new FirstLetterToUpperCaseFunctionTemplateHandler());
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadFunctionContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractFunctionTemplateContextHandler> defaultLoad = DefaultLoadFunctionContextHandlerDefault();
            IEnumerable<AbstractFunctionTemplateContextHandler> originalLoad = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractFunctionTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }
        public static IEnumerable<AbstractFunctionTemplateContextHandler> getAllFunctionContextHandler()
        {
            return DefaultLoadFunctionContextHandlerDefault();
        }

        public static IDictionary<String, AbstractFunctionTemplateContextHandler> getStartContextWrapperStringIndexedFunctionContextHandlerMap()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> result = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractFunctionTemplateContextHandler> getEndContextWrapperStringIndexedFunctionContextHandlerMap()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> result = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllFunctionContextHandlerSignature()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers =
                    getAllFunctionContextHandler();

            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.Append("Function context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);

            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static string getFunctionHandlerStartContextWordAtEarliestPositionInSubmittedString(string SubmittedString)
        {
            string result = null;
            if (!isSubmittedStringContainsAFunctionHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            var abatractTemplateContextHandlers =getAllFunctionContextHandler();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentStartWord = currentHandler.getStartContextStringWrapper();
                var currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) 
                    result = currentStartWord;
            }

            return result;
        }

        public static string getFunctionHandlerEndContextWordAtLatestPositionInSubmittedString(string submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            if (!isSubmittedStringContainsAnFunctionHandlerEndContextWord(submittedString)) return result;

            var abatractTemplateContextHandlers = getAllFunctionContextHandler();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentEndWord = currentHandler.getEndContextStringWrapper();
                var currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsAFunctionHandlerStartContextWord(string submittedString)
        {
            if (submittedString == null) return false;
            var templateContextHandlers =getAllFunctionContextHandler();
            return templateContextHandlers.Any(current => 
                submittedString.Contains(current.getStartContextStringWrapper()));
        }

        public static bool isSubmittedStringContainsAnFunctionHandlerEndContextWord(string submittedString)
        {
            if (submittedString == null) return false;
            var templateContextHandlers =getAllFunctionContextHandler();
            return templateContextHandlers.Any(current => submittedString.Contains(current.getEndContextStringWrapper()));
        }

        public static AbstractFunctionTemplateContextHandler getStartContextCorrespondingFunctionContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractFunctionTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedFunctionContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Function end context

        public static IEnumerable<AbstractTemplateContextHandler> getAllContextHandler()
        {
            List<AbstractTemplateContextHandler> result = new List<AbstractTemplateContextHandler>();
            result.AddRange(getAllColumnContextHandler());
            result.AddRange(getAllTableContextHandler());
            result.AddRange(getAllDatabaseContextHandler());
            return result;
        }

        public static string getAllContextHandlerSignature()
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append(getAllDatabaseContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllTableContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllColumnContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllFunctionContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            return stringBuilder.ToString();
        }

        private static IEnumerable<AbstractTemplateContextHandler> _allContextHandlerIterable = null;
        public static IEnumerable<AbstractTemplateContextHandler> getAllContextHandlerIterable()
        {
            if (_allContextHandlerIterable == null)
            {
                List<AbstractTemplateContextHandler> result = new List<AbstractTemplateContextHandler>();
                IEnumerable<AbstractDatabaseTemplateContextHandler> DatabaseHandlers = getAllDatabaseContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractTableTemplateContextHandler> TableHandlers = getAllTableContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in TableHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractColumnTemplateContextHandler> ColumnHandlers = getAllColumnContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in ColumnHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractFunctionTemplateContextHandler> functionHandlers = getAllFunctionContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in functionHandlers)
                {
                    result.Add(currentHandler);
                }

                _allContextHandlerIterable = result;
            }
            return _allContextHandlerIterable;
        }

        private static IDictionary<string, AbstractTemplateContextHandler> _startContextWrapperStringIndexedAllContextHandlerMap;
        public static IDictionary<string, AbstractTemplateContextHandler> getStartContextWrapperStringIndexedAllContextHandlerMap()
        {
            if (_startContextWrapperStringIndexedAllContextHandlerMap == null)
            {
                Dictionary<string, AbstractTemplateContextHandler> result = new Dictionary<string, AbstractTemplateContextHandler>();
                IEnumerable<AbstractTemplateContextHandler> DatabaseHandlers = getAllContextHandlerIterable();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
                }
                _startContextWrapperStringIndexedAllContextHandlerMap = result;
            }
            return _startContextWrapperStringIndexedAllContextHandlerMap;
        }

        private static IDictionary<string, AbstractTemplateContextHandler> _endContextWrapperStringIndexedAllContextHandlerMap;
        public IDictionary<string, AbstractTemplateContextHandler> getEndContextWrapperStringIndexedAllContextHandlerMap()
        {
            if (_endContextWrapperStringIndexedAllContextHandlerMap == null)
            {
                Dictionary<string, AbstractTemplateContextHandler> result = new Dictionary<string, AbstractTemplateContextHandler>();
                IEnumerable<AbstractTemplateContextHandler> DatabaseHandlers = getAllContextHandlerIterable();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
                }
                _endContextWrapperStringIndexedAllContextHandlerMap = result;
            }
            return _endContextWrapperStringIndexedAllContextHandlerMap;
        }



        public static string getHandlerStartContextWordAtEarliestPositionInSubmittedString(string SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAHandlerStartContextWord(SubmittedString)) return result;
            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            var abatractTemplateContextHandlers =getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentStartWord = currentHandler.getStartContextStringWrapper();
                var currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition)))
                {
                    EarliestPosition = currentIndexOf;
                    result = currentStartWord;
                }
            }

            return result;
        }

        public static string getHandlerStartContextWordAtLattestPositionInSubmittedString(string SubmittedString)
        {
            string result = null;
            if (!isSubmittedStringContainsAHandlerStartContextWord(SubmittedString)) return result;
            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            var abatractTemplateContextHandlers = getAllContextHandlerIterable();
            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentStartWord = currentHandler.getStartContextStringWrapper();
                var currentIndexOf = SubmittedString.LastIndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf > EarliestPosition)))
                {
                    EarliestPosition = currentIndexOf;
                    result = currentStartWord;
                }
            }

            return result;
        }

        public static string getHandlerEndContextWordAtEarliestPositionInSubmittedString(string submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            if (!isSubmittedStringContainsAnHandlerEndContextWord(submittedString)) return result;
            var abatractTemplateContextHandlers = getAllContextHandlerIterable();
            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                var currentEndWord = currentHandler.getEndContextStringWrapper();
                var currentlastIndexOf = submittedString.IndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf < EarliestPosition)))
                {
                    EarliestPosition = currentlastIndexOf;
                    result = currentEndWord;
                }
            }
            return result;
        }

        public static string getHandlerEndContextWordAtLatestPositionInSubmittedString(string submittedString)
        {
            string result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            if (!isSubmittedStringContainsAnHandlerEndContextWord(submittedString)) return result;
            var abatractTemplateContextHandlers =getAllContextHandlerIterable();
            int currentOffset = 0;
            string submittedStringCopy = submittedString;
            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                string currentEndWord = currentHandler.getEndContextStringWrapper();
                int currentSubmittedCopyEarliestIndexOf = submittedStringCopy.IndexOf(currentEndWord, StringComparison.Ordinal);
                var currentlastIndexOf = currentSubmittedCopyEarliestIndexOf + currentOffset;
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition)))
                {
                    EarliestPosition = currentlastIndexOf;
                    result = currentEndWord;
                    submittedStringCopy.Substring(currentSubmittedCopyEarliestIndexOf + currentEndWord.Length);
                }
            }
            return result;
        }

        public static bool isSubmittedStringContainsAHandlerStartContextWord(string submittedString)
        {
            if (submittedString == null) return false;
            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers = getAllContextHandlerIterable();
            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static int countStartContextWordInSubmittedString(String submittedString)
        {
            int result = 0;
            if (submittedString == null) return result;
            if (!submittedString.Any()) return result;
            String FirstStartContextWordTrimmedString = submittedString;
            String startContextWord = getHandlerStartContextWordAtEarliestPositionInSubmittedString(FirstStartContextWordTrimmedString);
            while (startContextWord != null)
            {
                FirstStartContextWordTrimmedString = StringUtilities.
                    getRightPartOfSubmittedStringAfterFirstSearchedWordOccurence(
                            FirstStartContextWordTrimmedString, startContextWord);
                startContextWord =
                        getHandlerStartContextWordAtEarliestPositionInSubmittedString(
                                FirstStartContextWordTrimmedString);
                result++;
            }
            return result;
        }

        public static int countEndContextWordInSubmittedString(String submittedString)
        {
            int result = 0;
            if (submittedString == null) return result;
            if (!submittedString.Any()) return result;
            String FirstEndContextWordTrimmedString = submittedString;
            String endContextWord = getHandlerEndContextWordAtEarliestPositionInSubmittedString(submittedString);
            while (endContextWord != null)
            {
                FirstEndContextWordTrimmedString = StringUtilities.
                    getRightPartOfSubmittedStringAfterFirstSearchedWordOccurence(
                            FirstEndContextWordTrimmedString, endContextWord);
                endContextWord =
                        getHandlerEndContextWordAtEarliestPositionInSubmittedString(
                                FirstEndContextWordTrimmedString);
                result++;
            }
            return result;
        }

        public static string getStartContextCorrespondingEndContextWrapper(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedAllContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper].getEndContextStringWrapper();
        }

        public static AbstractTemplateContextHandler getStartContextCorrespondingContextHandler(string StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<string, AbstractTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedAllContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];
        }
    }
}
