using DBTemplateHandler.Core.TemplateHandlers.Context.Columns;
using System;
using System.Collections.Generic;
using System.Text;

namespace DBTemplateHandler.Core.TemplateHandlers.Context
{
    public class TemplateContextHandlerRegister
    {
        private readonly IList<ITemplateContextHandler> _contextHandlers =
            new List<ITemplateContextHandler>()
            {
            new AutoColumnIndexColumnContextHandler(),
            new ColumnIndexColumnContextHandler(),
            new ColumnNameColumnContextHandler(),
            new ColumnValueConvertTypeColumnContextHandler(),
            new ColumnValueTypeColumnContextHandler(),
            new IsAutoColumnAFirstAutoColumnContextHandler(),
            new IsAutoColumnALastAutoColumnContextHandler(),
            new IsAutoColumnNotAFirstAutoColumnContextHandler(),
            new IsAutoColumnNotALastAutoColumnContextHandler(),
            new IsColumnAFirstColumnContextHandler(),
            new IsColumnALastColumnContextHandler(),
            new IsColumnAutoGeneratedValueColumnContextHandler(),
            new IsColumnNotAFirstColumnContextHandler(),
            new IsColumnNotALastColumnContextHandler(),
            new IsColumnNotAutoGeneratedValueColumnContextHandler2(),
            new IsColumnNotNullValueColumnContextHandler(),
            new IsColumnNotPrimaryKeyColumnContextHandler(),
            new IsColumnPrimaryKeyColumnContextHandler(),
            new IsNotAutoColumnAFirstAutoColumnContextHandler(),
            new IsNotAutoColumnALastAutoColumnContextHandler(),
            new IsNotAutoColumnNotAFirstAutoColumnContextHandler(),
            new IsNotAutoColumnNotALastAutoColumnContextHandler(),
            new IsNotNullColumnAFirstAutoColumnContextHandler(),
            new IsNotNullColumnALastAutoColumnContextHandler(),
            new IsNotPrimaryColumnAFirstAutoColumnContextHandler(),
            new IsNotPrimaryColumnALastAutoColumnContextHandler(),
            new IsNotPrimaryColumnNotAFirstAutoColumnContextHandler(),
            new IsNotPrimaryColumnNotALastAutoColumnContextHandler(),
            new IsPrimaryColumnAFirstAutoColumnContextHandler(),
            new IsPrimaryColumnALastAutoColumnContextHandler(),
            new IsPrimaryColumnNotAFirstAutoColumnContextHandler(),
            new IsPrimaryColumnNotALastAutoColumnContextHandler(),
            new NotAutoColumnIndexColumnContextHandler(),
            new NotNullColumnIndexColumnContextHandler(),
            new NotPrimaryColumnIndexColumnContextHandler(),
            new PrimaryColumnIndexColumnContextHandler(),
            }; 


        public IList<ITemplateContextHandler> GetHandlers()
        {
            return new List<ITemplateContextHandler>();
        }
    }
}
