using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DBTemplateHandler.Core.TemplateHandlers.Columns;
using DBTemplateHandler.Core.TemplateHandlers.Context.Database;
using DBTemplateHandler.Core.TemplateHandlers.Context.Functions;
using DBTemplateHandler.Core.TemplateHandlers.Context.Tables;
using DBTemplateHandler.Core.TemplateHandlers.Utilities;

namespace DBTemplateHandler.Core.TemplateHandlers.Context
{
    public class TemplateContextHandlerPackageProvider
    {
        private const string NEW_LINE_CHAR = "\t\n";

        //private static Logger logger = Logger.getLogger(TemplateContextHandlerPackageProvider.class);

        //Column part
        private static List<AbstractColumnTemplateContextHandler> allColumnContextHandlerArrayList = null;
        private static IEnumerable<AbstractColumnTemplateContextHandler> DefaultLoadColumnContextHandlerDefault()
        {
            List<AbstractColumnTemplateContextHandler> result = new List<AbstractColumnTemplateContextHandler>();
            result.Add((AbstractColumnTemplateContextHandler)(new AutoColumnIndexColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new ColumnIndexColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new ColumnNameColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new ColumnValueConvertTypeColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new ColumnValueTypeColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsAutoColumnAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsAutoColumnALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsAutoColumnNotAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsAutoColumnNotALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnAFirstColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnALastColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnAutoGeneratedValueColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnNotAFirstColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnNotALastColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnNotAutoGeneratedValueColumnContextHandler2()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnNotNullValueColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnNotPrimaryKeyColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsColumnPrimaryKeyColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotAutoColumnAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotAutoColumnALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotAutoColumnNotAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotAutoColumnNotALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotNullColumnAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotNullColumnALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotPrimaryColumnAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotPrimaryColumnALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotPrimaryColumnNotAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsNotPrimaryColumnNotALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsPrimaryColumnAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsPrimaryColumnALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsPrimaryColumnNotAFirstAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new IsPrimaryColumnNotALastAutoColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new NotAutoColumnIndexColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new NotNullColumnIndexColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new NotPrimaryColumnIndexColumnContextHandler()));
            result.Add((AbstractColumnTemplateContextHandler)(new PrimaryColumnIndexColumnContextHandler()));
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadColumnContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractColumnTemplateContextHandler> defaultLoad = DefaultLoadColumnContextHandlerDefault();
            IEnumerable<AbstractColumnTemplateContextHandler> originalLoad = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractColumnTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }

        public static IEnumerable<AbstractColumnTemplateContextHandler> getAllColumnContextHandler()
        {
            return DefaultLoadColumnContextHandlerDefault();
        }

        public static IDictionary<String, AbstractColumnTemplateContextHandler> getStartContextWrapperStringIndexedColumnContextHandlerMap()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> result =
                    new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractColumnTemplateContextHandler> getEndContextWrapperStringIndexedColumnContextHandlerMap()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers = getAllColumnContextHandler();
            Dictionary<String, AbstractColumnTemplateContextHandler> result =
                    new Dictionary<String, AbstractColumnTemplateContextHandler>();
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllColumnContextHandlerSignature()
        {
            IEnumerable<AbstractColumnTemplateContextHandler> handlers =
                    getAllColumnContextHandler();

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("Column context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);
            foreach (AbstractColumnTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getColumnHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAColumnHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getColumnHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnColumnHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsAColumnHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnColumnHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractColumnTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllColumnContextHandler();

            foreach (AbstractColumnTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractColumnTemplateContextHandler getStartContextCorrespondingColumnContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractColumnTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedColumnContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Column Part End


        //Table Part
        private static List<AbstractTableTemplateContextHandler> allTableContextHandlerArrayList = null;
        private static IEnumerable<AbstractTableTemplateContextHandler> DefaultLoadTableContextHandlerDefault()
        {
            List<AbstractTableTemplateContextHandler> result = new List<AbstractTableTemplateContextHandler>();
            result.Add((AbstractTableTemplateContextHandler)(new ForEachAutoGeneratedValueColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new ForEachColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new ForEachNotAutoGeneratedValueColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new ForEachNotNullColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new ForEachNotPrimaryKeyColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new ForEachPrimaryKeyColumnTableContextHandler()));
            result.Add((AbstractTableTemplateContextHandler)(new TableNameTableContextHandler()));
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadTableContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractTableTemplateContextHandler> defaultLoad = DefaultLoadTableContextHandlerDefault();
            IEnumerable<AbstractTableTemplateContextHandler> originalLoad = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractTableTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }

        public static IEnumerable<AbstractTableTemplateContextHandler> getAllTableContextHandler()
        {
            return DefaultLoadTableContextHandlerDefault();
        }

        public static IDictionary<String, AbstractTableTemplateContextHandler> getStartContextWrapperStringIndexedTableContextHandlerMap()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> result = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractTableTemplateContextHandler> getEndContextWrapperStringIndexedTableContextHandlerMap()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers = getAllTableContextHandler();
            Dictionary<String, AbstractTableTemplateContextHandler> result = new Dictionary<String, AbstractTableTemplateContextHandler>();
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllTableContextHandlerSignature()
        {
            IEnumerable<AbstractTableTemplateContextHandler> handlers =
                    getAllTableContextHandler();

            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("Table context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);
            foreach (AbstractTableTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getTableHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsATableHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getTableHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnTableHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsATableHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnTableHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTableTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllTableContextHandler();

            foreach (AbstractTableTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractTableTemplateContextHandler getStartContextCorrespondingTableContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractTableTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedTableContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //End Table context


        //Database context Handler Part
        private static List<AbstractDatabaseTemplateContextHandler> allDatabaseContextHandlerArrayList = null;
        private static IEnumerable<AbstractDatabaseTemplateContextHandler> DefaultLoadDatabaseContextHandlerDefault()
        {
            List<AbstractDatabaseTemplateContextHandler> result = new List<AbstractDatabaseTemplateContextHandler>();
            result.Add((AbstractDatabaseTemplateContextHandler)(new DatabaseNameDatabaseContextHandler()));
            result.Add((AbstractDatabaseTemplateContextHandler)(new ForEachTableDatabaseContextHandler()));
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadDatabaseContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractDatabaseTemplateContextHandler> defaultLoad = DefaultLoadDatabaseContextHandlerDefault();
            IEnumerable<AbstractDatabaseTemplateContextHandler> originalLoad = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractDatabaseTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }
        public static IEnumerable<AbstractDatabaseTemplateContextHandler> getAllDatabaseContextHandler()
        {
            return DefaultLoadDatabaseContextHandlerDefault();
        }

        public static IDictionary<String, AbstractDatabaseTemplateContextHandler> getStartContextWrapperStringIndexedDatabaseContextHandlerMap()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> result = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractDatabaseTemplateContextHandler> getEndContextWrapperStringIndexedDatabaseContextHandlerMap()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers = getAllDatabaseContextHandler();
            Dictionary<String, AbstractDatabaseTemplateContextHandler> result = new Dictionary<String, AbstractDatabaseTemplateContextHandler>();
            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllDatabaseContextHandlerSignature()
        {
            IEnumerable<AbstractDatabaseTemplateContextHandler> handlers =
                    getAllDatabaseContextHandler();

            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.Append("Database context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getDatabaseHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsADatabaseHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractDatabaseTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getDatabaseHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnDatabaseHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractDatabaseTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsADatabaseHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractDatabaseTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnDatabaseHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractDatabaseTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllDatabaseContextHandler();

            foreach (AbstractDatabaseTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractDatabaseTemplateContextHandler getStartContextCorrespondingDatabaseContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractDatabaseTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedDatabaseContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Database end context

        //Function start context
        private static List<AbstractFunctionTemplateContextHandler> allFunctionContextHandlerArrayList = null;
        private static IEnumerable<AbstractFunctionTemplateContextHandler> DefaultLoadFunctionContextHandlerDefault()
        {
            List<AbstractFunctionTemplateContextHandler> result = new List<AbstractFunctionTemplateContextHandler>();
            result.Add((AbstractFunctionTemplateContextHandler)(new FirstLetterToUpperCaseFunctionTemplateHandler()));
            return result;
        }

        public static List<String>
            GetDefaultLoadAndOriginalLoadFunctionContextHandlerDifferenceSignatureArray()
        {
            List<String> result = new List<String>();
            IEnumerable<AbstractFunctionTemplateContextHandler> defaultLoad = DefaultLoadFunctionContextHandlerDefault();
            IEnumerable<AbstractFunctionTemplateContextHandler> originalLoad = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> defaultLoadHashMap = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentDefaultLoad in defaultLoad)
            {
                defaultLoadHashMap.Add(currentDefaultLoad.getTemplateHandlerSignature(), currentDefaultLoad);
            }

            foreach (AbstractFunctionTemplateContextHandler currentOriginalLoad in originalLoad)
            {
                if (!defaultLoadHashMap.ContainsKey(currentOriginalLoad.getTemplateHandlerSignature()))
                {
                    result.Add(currentOriginalLoad.getTemplateHandlerSignature());
                }
            }
            return result;
        }
        public static IEnumerable<AbstractFunctionTemplateContextHandler> getAllFunctionContextHandler()
        {
            return DefaultLoadFunctionContextHandlerDefault();
        }

        public static IDictionary<String, AbstractFunctionTemplateContextHandler> getStartContextWrapperStringIndexedFunctionContextHandlerMap()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> result = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static IDictionary<String, AbstractFunctionTemplateContextHandler> getEndContextWrapperStringIndexedFunctionContextHandlerMap()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers = getAllFunctionContextHandler();
            Dictionary<String, AbstractFunctionTemplateContextHandler> result = new Dictionary<String, AbstractFunctionTemplateContextHandler>();
            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
            }
            return result;
        }

        public static String getAllFunctionContextHandlerSignature()
        {
            IEnumerable<AbstractFunctionTemplateContextHandler> handlers =
                    getAllFunctionContextHandler();

            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.Append("Function context handler signature");
            stringBuilder.Append(NEW_LINE_CHAR);

            foreach (AbstractFunctionTemplateContextHandler currentHandler in handlers)
            {
                stringBuilder.Append(currentHandler.getTemplateHandlerSignature());
                stringBuilder.Append(NEW_LINE_CHAR);
            }
            return stringBuilder.ToString();
        }

        public static String getFunctionHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAFunctionHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractFunctionTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllFunctionContextHandler();

            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition))) result = currentStartWord;
            }

            return result;
        }

        public static String getFunctionHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnFunctionHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractFunctionTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllFunctionContextHandler();

            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.LastIndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition))) result = currentEndWord;
            }

            return result;
        }

        public static bool isSubmittedStringContainsAFunctionHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractFunctionTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllFunctionContextHandler();

            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnFunctionHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractFunctionTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllFunctionContextHandler();

            foreach (AbstractFunctionTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static AbstractFunctionTemplateContextHandler getStartContextCorrespondingFunctionContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractFunctionTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedFunctionContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];

        }
        //Function end context

        public static IEnumerable<AbstractTemplateContextHandler> getAllContextHandler()
        {
            List<AbstractTemplateContextHandler> result = new List<AbstractTemplateContextHandler>();
            result.AddRange(getAllColumnContextHandler());
            result.AddRange(getAllTableContextHandler());
            result.AddRange(getAllDatabaseContextHandler());
            return result;
        }

        public static String getAllContextHandlerSignature()
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append(getAllDatabaseContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllTableContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllColumnContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            stringBuilder.Append(getAllFunctionContextHandlerSignature());
            stringBuilder.Append(NEW_LINE_CHAR);
            return stringBuilder.ToString();
        }

        private static IEnumerable<AbstractTemplateContextHandler> _allContextHandlerIterable = null;
        public static IEnumerable<AbstractTemplateContextHandler> getAllContextHandlerIterable()
        {
            if (_allContextHandlerIterable == null)
            {
                List<AbstractTemplateContextHandler> result = new List<AbstractTemplateContextHandler>();
                IEnumerable<AbstractDatabaseTemplateContextHandler> DatabaseHandlers = getAllDatabaseContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractTableTemplateContextHandler> TableHandlers = getAllTableContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in TableHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractColumnTemplateContextHandler> ColumnHandlers = getAllColumnContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in ColumnHandlers)
                {
                    result.Add(currentHandler);
                }
                IEnumerable<AbstractFunctionTemplateContextHandler> functionHandlers = getAllFunctionContextHandler();
                foreach (AbstractTemplateContextHandler currentHandler in functionHandlers)
                {
                    result.Add(currentHandler);
                }

                _allContextHandlerIterable = result;
            }
            return _allContextHandlerIterable;
        }

        private static IDictionary<String, AbstractTemplateContextHandler> _startContextWrapperStringIndexedAllContextHandlerMap;
        public static IDictionary<String, AbstractTemplateContextHandler> getStartContextWrapperStringIndexedAllContextHandlerMap()
        {
            if (_startContextWrapperStringIndexedAllContextHandlerMap == null)
            {
                Dictionary<String, AbstractTemplateContextHandler> result = new Dictionary<String, AbstractTemplateContextHandler>();
                IEnumerable<AbstractTemplateContextHandler> DatabaseHandlers = getAllContextHandlerIterable();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler.getStartContextStringWrapper(), currentHandler);
                }
                _startContextWrapperStringIndexedAllContextHandlerMap = result;
            }
            return _startContextWrapperStringIndexedAllContextHandlerMap;
        }

        private static IDictionary<String, AbstractTemplateContextHandler> _endContextWrapperStringIndexedAllContextHandlerMap;
        public IDictionary<String, AbstractTemplateContextHandler> getEndContextWrapperStringIndexedAllContextHandlerMap()
        {
            if (_endContextWrapperStringIndexedAllContextHandlerMap == null)
            {
                Dictionary<String, AbstractTemplateContextHandler> result = new Dictionary<String, AbstractTemplateContextHandler>();
                IEnumerable<AbstractTemplateContextHandler> DatabaseHandlers = getAllContextHandlerIterable();
                foreach (AbstractTemplateContextHandler currentHandler in DatabaseHandlers)
                {
                    result.Add(currentHandler.getEndContextStringWrapper(), currentHandler);
                }
                _endContextWrapperStringIndexedAllContextHandlerMap = result;
            }
            return _endContextWrapperStringIndexedAllContextHandlerMap;
        }



        public static String getHandlerStartContextWordAtEarliestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.IndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf < EarliestPosition)))
                {
                    EarliestPosition = currentIndexOf;
                    result = currentStartWord;
                }
            }

            return result;
        }

        public static String getHandlerStartContextWordAtLattestPositionInSubmittedString(String SubmittedString)
        {
            String result = null;
            if (!isSubmittedStringContainsAHandlerStartContextWord(SubmittedString)) return result;

            int EarliestPosition = -1;
            if (SubmittedString == null) return null;
            int currentIndexOf;
            String currentStartWord = "";

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentStartWord = currentHandler.getStartContextStringWrapper();
                currentIndexOf = SubmittedString.LastIndexOf(currentStartWord, StringComparison.Ordinal);
                if (currentIndexOf >= 0 && ((EarliestPosition == -1) || (currentIndexOf > EarliestPosition)))
                {
                    EarliestPosition = currentIndexOf;
                    result = currentStartWord;
                }
            }

            return result;
        }

        public static String getHandlerEndContextWordAtEarliestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                currentlastIndexOf = submittedString.IndexOf(currentEndWord, StringComparison.Ordinal);
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf < EarliestPosition)))
                {
                    EarliestPosition = currentlastIndexOf;
                    result = currentEndWord;
                }
            }

            return result;
        }

        public static String getHandlerEndContextWordAtLatestPositionInSubmittedString(String submittedString)
        {
            String result = null;
            int EarliestPosition = -1;
            if (submittedString == null) return null;
            int currentlastIndexOf;
            String currentEndWord = "";

            if (!isSubmittedStringContainsAnHandlerEndContextWord(submittedString)) return result;

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();
            int currentOffset = 0;
            String submittedStringCopy = submittedString;
            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                currentEndWord = currentHandler.getEndContextStringWrapper();
                int currentSubmittedCopyEarliestIndexOf = submittedStringCopy.IndexOf(currentEndWord, StringComparison.Ordinal);
                currentlastIndexOf = currentSubmittedCopyEarliestIndexOf + currentOffset;
                if (currentlastIndexOf >= 0 && ((EarliestPosition == -1) || (currentlastIndexOf > EarliestPosition)))
                {
                    EarliestPosition = currentlastIndexOf;
                    result = currentEndWord;
                    submittedStringCopy.Substring(currentSubmittedCopyEarliestIndexOf + currentEndWord.Length);
                }
            }

            return result;
        }

        public static bool isSubmittedStringContainsAHandlerStartContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getStartContextStringWrapper())) return true;
            }
            return false;
        }

        public static bool isSubmittedStringContainsAnHandlerEndContextWord(String submittedString)
        {
            if (submittedString == null) return false;

            IEnumerable<AbstractTemplateContextHandler> abatractTemplateContextHandlers =
                    TemplateContextHandlerPackageProvider.getAllContextHandlerIterable();

            foreach (AbstractTemplateContextHandler currentHandler in abatractTemplateContextHandlers)
            {
                if (submittedString.Contains(currentHandler.getEndContextStringWrapper())) return true;
            }
            return false;
        }

        public static int countStartContextWordInSubmittedString(String submittedString)
        {
            int result = 0;
            if (submittedString == null) return result;
            if (!submittedString.Any()) return result;
            String FirstStartContextWordTrimmedString = submittedString;
            String startContextWord = getHandlerStartContextWordAtEarliestPositionInSubmittedString(FirstStartContextWordTrimmedString);
            while (startContextWord != null)
            {
                FirstStartContextWordTrimmedString = StringUtilities.
                    getRightPartOfSubmittedStringAfterFirstSearchedWordOccurence(
                            FirstStartContextWordTrimmedString, startContextWord);
                startContextWord =
                        getHandlerStartContextWordAtEarliestPositionInSubmittedString(
                                FirstStartContextWordTrimmedString);
                result++;
            }
            return result;
        }

        public static int countEndContextWordInSubmittedString(String submittedString)
        {
            int result = 0;
            if (submittedString == null) return result;
            if (!submittedString.Any()) return result;
            String FirstEndContextWordTrimmedString = submittedString;
            String endContextWord = getHandlerEndContextWordAtEarliestPositionInSubmittedString(submittedString);
            while (endContextWord != null)
            {
                FirstEndContextWordTrimmedString = StringUtilities.
                    getRightPartOfSubmittedStringAfterFirstSearchedWordOccurence(
                            FirstEndContextWordTrimmedString, endContextWord);
                endContextWord =
                        getHandlerEndContextWordAtEarliestPositionInSubmittedString(
                                FirstEndContextWordTrimmedString);
                result++;
            }
            return result;
        }

        public static String getStartContextCorrespondingEndContextWrapper(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedAllContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper].getEndContextStringWrapper();
        }

        public static AbstractTemplateContextHandler getStartContextCorrespondingContextHandler(String StartContextWrapper)
        {
            if (StartContextWrapper == null) return null;
            if (StartContextWrapper.Equals("")) return null;
            IDictionary<String, AbstractTemplateContextHandler> contextHandlerMap =
                    getStartContextWrapperStringIndexedAllContextHandlerMap();
            if (!contextHandlerMap.ContainsKey(StartContextWrapper)) return null;
            return contextHandlerMap[StartContextWrapper];
        }
    }
}
