using DBTemplateHandler.Core.Database;

namespace DBTemplateHandler.Core.UnitTests.ModelImplementation
{
    public class ColumnModelForTest : IColumnModel
    {
        public bool IsAutoGeneratedValue { get; set; }
        public bool IsNotNull { get; set; }
        public bool IsPrimaryKey { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int ValueMaxSize { get; set; }
        public ITableModel ParentTable { get; set; }
    }
}
