using System;
namespace DBTemplateHandler.Core.Database
{
    public class ColumnDescriptor
    {
        public ColumnDescriptor(string name,
                string type, bool isPrimaryKey)
        {
            Name = name;
            Type = type;
            IsPrimaryKey = isPrimaryKey;
        }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGeneratedValue { get; set; }

        private bool _NotNull;
        public bool is_NotNull()
        {
            return _NotNull;
        }

        public void set_NotNull(bool _NotNull)
        {
            this._NotNull = _NotNull;
        }

        //Template Handler specific properties
        public TableDescriptor ParentTable;
    }
}
