using System;
namespace DBTemplateHandler.Core.Database
{
    [Serializable]
    public class ColumnModel
    {
        public ColumnModel(string name,
                string type, bool isPrimaryKey)
        {
            Name = name;
            Type = type;
            IsPrimaryKey = isPrimaryKey;
        }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGeneratedValue { get; set; }
        public bool IsNotNull { get; set; }
        //Template Handler specific properties
        public TableModel ParentTable;
    }
}
