using System;
namespace DBTemplateHandler.Core.Database
{
    public class TableColumnDescriptionPOJO
    {
        public TableColumnDescriptionPOJO(String NameStr,
                String TypeStr, bool IsPrimaryKey)
        {
            _NameStr = NameStr;
            _TypeStr = TypeStr;
            _PrimaryKey = IsPrimaryKey;
        }

        private String _NameStr;
        public String get_NameStr()
        {
            return _NameStr;
        }

        public void set_NameStr(String _NameStr)
        {
            this._NameStr = _NameStr;
        }

        private String _TypeStr;
        public String get_TypeStr()
        {
            return _TypeStr;
        }

        public void set_TypeStr(String _TypeStr)
        {
            this._TypeStr = _TypeStr;
        }


        private bool _PrimaryKey;
        public bool is_PrimaryKey()
        {
            return _PrimaryKey;
        }

        public void set_PrimaryKey(bool _PrimaryKey)
        {
            this._PrimaryKey = _PrimaryKey;
        }

        private bool _AutoGeneratedValueBln;
        public bool is_AutoGeneratedValueBln()
        {
            return _AutoGeneratedValueBln;
        }

        public void set_AutoGeneratedValueBln(bool value)
        {
            this._AutoGeneratedValueBln = value;
        }

        private bool _NotNull;
        public bool is_NotNull()
        {
            return _NotNull;
        }

        public void set_NotNull(bool _NotNull)
        {
            this._NotNull = _NotNull;
        }

        //Template Handler specific properties
        public TableDescriptionPOJO ParentTable;
    }
}
